apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
        - name: register
          image: register:latest  
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: register-service
spec:
  selector:
    app: register
  ports:
    - protocol: TCP
      port: 5000   
      targetPort: 5000  
      nodePort: 30020   
  type: NodePort